### ISSUE TITLE
No Error Log and Fails Sending

### ISSUE THREAD

**Issue by stagfoo** [aschroder/Magento-SMTP-Pro-Email-Extension#130]
Hi,
I have used your plugin on another client website and it worked perfectly but i have set it up the same on new client site and I get this error. I would include more information but the error logs also don't get created? if there something i'm missing? Permissions maybe because i can't create logs?
```
Sending test email to your contact form address: sales@website.com.au from: sales@website.com.au. Unable to send test email.
Exception message was: Unable to read response, or response is empty
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.
Required database tables exist.
Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.
```

**Comment by aschroder** [comment]
that's typically caused by connectivity issues between your web server and
your smtp server - sometimes it's a firewall blocking it for example.

I suggest:
1) test with a different smtp server
2) check with you sys admin or web host support about any reasons why there
might be issues connecting to an external smtp server (on whatever port
you're trying).

**Comment by stagfoo** [comment]
I found out the issue was with `$host` i was using the SMTP instead of the API Endpoint sorry about that. Thanks for the help!
