### ISSUE TITLE
Patch 6788

### ISSUE THREAD

**Issue by chequille** [aschroder/Magento-SMTP-Pro-Email-Extension#135]
Dear Ashley, since Patch 6788 or Update to 1.9.2.2 SMTP Pro is not sending emails anymore. The only thing which is working is the RunSelf Test on the configuration pages.

Are you aware of this problem?
WIll there be a solution for it?

Please let us know.
Best regards
Jürgen

**Comment by Fuzzzzy** [comment]
Hello,

I'm having the same issue here.
Thanks for taking care.
Istvan

**Comment by aschroder** [comment]
Have you got any debug logging or exception/error showing for this?

**Comment by Fuzzzzy** [comment]
Maybe it was a variable issue with the email template. I've added the variables to be allowed. I could not test it yet. I'll let you know tomorrow. Thanks for your quick response!!!

**Comment by chequille** [comment]
Hi Ashley,

 

on my site it is working now. 

Unfortunately, I cannot say why.

After upgrading Magento, it did not work.

Therefore, I changed the email stuff to the standard queue with cron jobs and made all the other necessary changes to be made (adding permitted blocks etc.).

After all this and of course deleting the cache a couple of times I activated again the extension and it is working now.

 

Maybe deleting the cache on the server and not with the functions inside the Magento Backend did solve my problem, but I cannot confirm this.

I 

Best regards,

Jürgen

 

Von: Ashley Schroder [mailto:notifications@github.com] 
Gesendet: Freitag, 20. November 2015 04:41
An: aschroder/Magento-SMTP-Pro-Email-Extension <Magento-SMTP-Pro-Email-Extension@noreply.github.com>
Cc: chequille <js@chequille.de>
Betreff: Re: [Magento-SMTP-Pro-Email-Extension] Patch 6788 (#135)

 

Have you got any debug logging or exception/error showing for this?

**Comment by savla-jigs** [comment]
after applying patch 6788 module is not working anymore.

please check output what I get after self test

>Your connection to the SMTP server timed out. Please check with your host that outbound SMTP connections are allowed as this error is most commonly caused when a host blocks outbound connections. This is probably not a bug, please do not email extension support until you have checked with your server admin or host.
>Default templates exist.
>Email communications are enabled.


however previously it was working fine.

please do needful.

Regards,
Jigar

**Comment by moyed** [comment]
I'm having same issue " Please check with your host that outbound SMTP connections are allowed as this error is most commonly caused when a host blocks outbound connections"

Please help.

**Comment by ravinahudda** [comment]
Hell Team,

I Love to SMTP pro version and it was working for me. i did use it for many projects. but now i have issue in magento version: 1.9.2.4
When i test connection than its showing errors like:

Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.
SMTP Pro Self Test Results
Sending test email to your contact form address: support@domainname from: support@domainname.com. Unable to send test email.
Your connection to the SMTP server timed out. Please check with your host that outbound SMTP connections are allowed as this error is most commonly caused when a host blocks outbound connections. This is probably not a bug, please do not email extension support until you have checked with your server admin or host.
Default templates exist.
Email communications are enabled.

Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.

Kindly let assist me, stop my project deliver due to SMTP only.

Thanks

**Comment by pawan1101** [comment]
Your connection to the SMTP server timed out. Please check with your host that outbound SMTP connections are allowed as this error is most commonly caused when a host blocks outbound connections. This is probably not a bug, please do not email extension support until you have checked with your server admin or host.

**Comment by ravinahudda** [comment]
Thanks pawan.

too late but have reply

**Comment by ravinahudda** [comment]
ok

**Comment by sandermangel** [comment]
@chequille this issue has been open for a while. Do you have any more information to reproduce the issue?
