### ISSUE TITLE
SMTP "Login" option does not show Username/Password fields

### ISSUE THREAD

**Issue by augustasas** [aschroder/Magento-SMTP-Pro-Email-Extension#137]
Hello,

I have installed this module on Magento 1.6.2.0.
When I select "Custom SMTP" --> "Login", I do not see Username and Password fields.
Here is a screenshot.
![no username/password field](http://i.imgur.com/sHQoaL5.jpg)

In order to fill those fields I used Chrome's developer tools (F12) and made them visible + enabled.

Any suggestion why they are hidden by default?

Thank you
Augustas

**Comment by gido** [comment]
Hi,

I get the same issue with an old Magento (1.5.x) and latest version of this module (2.0.7). It looks like [this particular depends](https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension/blame/master/app/code/local/Aschroder/SMTPPro/etc/system.xml#L147) was implemented since Magento 1.7 (based on [this source](http://stackoverflow.com/a/11828501/53338)).

**Comment by sandermangel** [comment]
By now 1.5 is quite an old version of Magento and not supported anymore.
the only solution is to use an old version of the module which I wouldn't recommend
