### ISSUE TITLE
One email breaks all

### ISSUE THREAD

**Issue by gulshankumar** [aschroder/Magento-SMTP-Pro-Email-Extension#139]
With multistore website, stops sending emails for all stores if exception in one email from any store.

Is there any way to continue sending next emails if there is some error in first email.

**Comment by jg-development** [comment]
Hi,
the only fast solution is for me to "continue" with the mail sending.
In the Queue.php change the "return false" to "continue".
```
                catch (Exception $e) {
                    unset($mailer);
                    $oldDevMode = Mage::getIsDeveloperMode();
                    Mage::setIsDeveloperMode(true);
                    Mage::logException($e);
                    Mage::setIsDeveloperMode($oldDevMode);

                    return false;
                }
```

```
                catch (Exception $e) {
                    unset($mailer);
                    $oldDevMode = Mage::getIsDeveloperMode();
                    Mage::setIsDeveloperMode(true);
                    Mage::logException($e);
                    Mage::setIsDeveloperMode($oldDevMode);

                    continue;
                }
```

The mail is not deleted from the queue.

Greetings Jan

**Comment by gulshankumar** [comment]
Thanks 

Do you think this should be implemented in extension's new release?

**Comment by jg-development** [comment]
Hi,
no way... in the catch block should be an exception event.
This event could either have a counter how often the email was tried too send or just
how old the mail is. For example:
If the mail is 2 h old in can be deleted.
And then deleting the mail itself of course ;-)

Greetings Jan

**Comment by gulshankumar** [comment]
Hi,

That is fine, but there is nothing which can notify me if any issue happens with mail.
This just stops sending email and logs exception in exception.log. No one can identify what is going wrong until its too late to send confirmation emails.

**Comment by hartmut-ltd** [comment]
Hi, one of my clients has got the same issue. I could track it down to

    catch (Exception $e) {
        <...>
        return false;
    }

, too.
In my client's case they are using a custom smtp - so it's all processed by Zend\Mail - which e.g. in a perfectly common cenario:
- customer typo in the email address domain (@smartarif24.de instead of @smarttarif24.de) will cause 

    Zend_Mail_Protocol_Exception: Requested action not taken: mailbox unavailable
    invalid DNS MX or A/AAAA resource record
    in /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail/Protocol/Abstract.php:431 

and therefore block the whole queue from being processed.
Same as with @gulshankumar it took quite long to notice, track down and fix - so lot's of customers didn't receive confirmation mails anymore.
Even with an event as suggested by @jg-development and e.g. any email queue error notification alert by e.g. email - it's still causing much trouble and delay by blocking up the queue completely.

I would rather vote for `continue` over `return false;` for the sake of not blocking up the whole queue.
An 'attempts' col and kind of a 'max_retries' setting would make most sense though I guess...

So how about adding a new table to add and count message processing attempts - along with a new setting for the max attempts for a start?

**Comment by sandermangel** [comment]
This issue has been fixed a while back by a PR, closing this issue
