### ISSUE TITLE
Time difference of 2 hours in E-Mail Log

### ISSUE THREAD

**Issue by MartinKonVis** [aschroder/Magento-SMTP-Pro-Email-Extension#263]
Hello,

inside the E-Mail Log we get wrong times. The times are +2hours. The order overview shows the normal correct dates+times. Just the mail log area of the extension has +2hours.

Is this a know bug or some configuration issue?

Greetings,
Martin

**Comment by sandermangel** [comment]
Hi @MartinKonVis thank you for posting your question. 
This is not a known bug and most likely not due to the extension as it does nothing with the logging logic itself, it uses the Magento logging feature: https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension/blob/master/app/code/local/Aschroder/SMTPPro/Helper/Data.php#L28

This might be due to the time set on the server itself

**Comment by FelixKonVis** [comment]
Hi,

it's not the Magento log files but the smtppro_email_log table entries that seem to be the problem.

From what I found in the code:
1. The SMTP Pro E-Mail Log Grid uses the Magento Datetime renderer which takes into account the timezone. 

2. The SMTP Pro E-Mail Log Detail view displays the plain value of log_at.

3. The smtpro_email_log table uses CURRENT_TIMESTAMP to update the log_at column
This happens to be local time (GMT+2).

In our case the shop is running in GMT+2 (GMT+1 + DST) and we are seeing the correct time in the E-Mail details but another +2h rendered in the Grid.

Am I missing anything? This seems to be a bug since the log entries store the local time in log_at but the Grid expects the datetime in GMT.
